
FROM openjdk:17
COPY target/Boot-Project03-MiniProject03-UserMgmtAPI-UI.jar /usr/app/

WORKDIR /user/app/
EXPOSE 8082

ENTRYPOINT ["java", "-jar", "/Boot-Project03-MiniProject03-UserMgmtAPI-UI.jar"]

